// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2fKQAGCY80BA0ijAeqTfMfxYxMSbqtCg',
    appId: '1:1044144235536:web:2fb1becec0136c9cc31695',
    messagingSenderId: '1044144235536',
    projectId: 'class-backend-ff617',
    authDomain: 'class-backend-ff617.firebaseapp.com',
    storageBucket: 'class-backend-ff617.firebasestorage.app',
    measurementId: 'G-X9BQFC7Z4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAylnF9RwYjgX2veUO6VWvnb6R4kLhLOsI',
    appId: '1:1044144235536:android:2e5b2f9016aa28a2c31695',
    messagingSenderId: '1044144235536',
    projectId: 'class-backend-ff617',
    storageBucket: 'class-backend-ff617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjmFvSBQgjetyaS2ZDjW58yXyb-x5_hf8',
    appId: '1:1044144235536:ios:826f14842230dee4c31695',
    messagingSenderId: '1044144235536',
    projectId: 'class-backend-ff617',
    storageBucket: 'class-backend-ff617.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjmFvSBQgjetyaS2ZDjW58yXyb-x5_hf8',
    appId: '1:1044144235536:ios:826f14842230dee4c31695',
    messagingSenderId: '1044144235536',
    projectId: 'class-backend-ff617',
    storageBucket: 'class-backend-ff617.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2fKQAGCY80BA0ijAeqTfMfxYxMSbqtCg',
    appId: '1:1044144235536:web:d8405679e25aad36c31695',
    messagingSenderId: '1044144235536',
    projectId: 'class-backend-ff617',
    authDomain: 'class-backend-ff617.firebaseapp.com',
    storageBucket: 'class-backend-ff617.firebasestorage.app',
    measurementId: 'G-FXRBZW5Y58',
  );

}